
services:
  spark-local:
    image: spark:3.5.7-python3
    container_name: spark-local
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/spark/bin
    ports:
      - "4040:4040"
    volumes:
      - ./src:/opt/app
      - ./data:/opt/data
      - ./output:/opt/output
      - ./events:/opt/spark-events
    command: ["bash", "-lc", "sleep infinity"]
    networks: [spark-net]

  spark-history:
    image: spark:3.5.7-python3
    container_name: spark-history
    depends_on:
      - spark-local
    ports:
      - "18080:18080"
    volumes:
      - ./events:/opt/spark-events
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark-events -Dspark.history.ui.port=18080
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.history.HistoryServer"]
    networks: [spark-net]

networks:
  spark-net:
    driver: bridge
